name: run main.py

on:
  schedule:
    #- cron: '*/5 * * * *'
    - cron: '0 0 * * *'
  push:
    branches:
      - main   # ou a branch onde você deseja rodar o script
  pull_request:
    branches:
      - main   # ou a branch de pull request
  workflow_dispatch:  # Permite a execução manual do workflow
jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar o python
        uses: actions/setup-python@v4

      - name: instalar os pacotes do requirements.txt
        run: python -m pip install -r requirements.txt

      - name: executar arquivo de request test!
        run: python main.py